// Auto-generated by Agent Tester
var testData = {
  "lastUpdate": "2026-02-05T14:30:00",
  "sheetTitle": "Testy_Lista",
  "sheetUrl": "https://docs.google.com/spreadsheets/d/1wFlv0KrT4JNTXAnGO4mwtDXPkh2dIxQzfM0VCXxA1jA",
  "sheetId": "1wFlv0KrT4JNTXAnGO4mwtDXPkh2dIxQzfM0VCXxA1jA",
  "agentStatus": {
    "isRunning": false,
    "currentAction": "Oczekiwanie na uruchomienie agenta testera...",
    "lastAction": "",
    "finished": false,
    "startedAt": null
  },
  "summary": {
    "total": 0,
    "passed": 0,
    "failed": 0,
    "blocked": 0,
    "inProgress": 0
  },
  "currentTest": null,
  "tests": []
};
