/**
 * Sprawdza czy agent startuje jako nowa sesja czy wznowienie po błędzie
 *
 * Logika:
 * - Jeśli isRunning=true i lastUpdate < 5 min → CONTINUE_SESSION (restart po błędzie)
 * - Jeśli isRunning=true i lastUpdate > 5 min → FRESH_START (stara zawieszona sesja)
 * - Jeśli isRunning=false → FRESH_START (normalna nowa sesja)
 *
 * Output:
 * Wypisuje "FRESH_START" lub "CONTINUE_SESSION" do stdout
 */

const fs = require('fs');
const path = require('path');

const MONITOR_FILE = path.join(__dirname, '..', 'monitor', 'tests-data.js');
const RESTART_THRESHOLD_MS = 5 * 60 * 1000; // 5 minut

function checkRestart() {
    try {
        // Brak pliku = nowa sesja
        if (!fs.existsSync(MONITOR_FILE)) {
            console.log('FRESH_START');
            console.error('INFO: Brak pliku tests-data.js - nowa sesja');
            return;
        }

        // Odczytaj plik
        const content = fs.readFileSync(MONITOR_FILE, 'utf8');
        const match = content.match(/var testData\s*=\s*(\{[\s\S]*\});?\s*$/);

        if (!match) {
            console.log('FRESH_START');
            console.error('INFO: Nie można sparsować tests-data.js - nowa sesja');
            return;
        }

        let testData;
        try {
            testData = JSON.parse(match[1]);
        } catch (e) {
            console.log('FRESH_START');
            console.error('INFO: Błąd JSON - nowa sesja');
            return;
        }

        const agentStatus = testData.agentStatus || {};

        // Jeśli sesja nie była uruchomiona lub zakończona = nowa sesja
        if (!agentStatus.isRunning || agentStatus.finished) {
            console.log('FRESH_START');
            console.error('INFO: Poprzednia sesja zakończona - nowa sesja');
            return;
        }

        // Sesja była uruchomiona - sprawdź jak dawno
        const lastUpdate = testData.lastUpdate;
        if (!lastUpdate) {
            console.log('FRESH_START');
            console.error('INFO: Brak lastUpdate - nowa sesja');
            return;
        }

        const lastUpdateTime = new Date(lastUpdate).getTime();
        const now = Date.now();
        const ageMs = now - lastUpdateTime;

        if (ageMs < RESTART_THRESHOLD_MS) {
            // Ostatnia aktualizacja < 5 min = to restart po błędzie
            const ageSec = Math.round(ageMs / 1000);
            console.log('CONTINUE_SESSION');
            console.error(`INFO: Wykryto restart po błędzie (lastUpdate ${ageSec}s temu)`);
            console.error(`INFO: Poprzedni test: ${testData.currentTest?.code || 'brak'}`);
            console.error(`INFO: Wykonane testy: ${testData.tests?.length || 0}`);

            // Zaktualizuj status - zaznacz że wznawiamy
            const nowStr = new Date().toISOString().slice(0, 19);
            testData.lastUpdate = nowStr;
            testData.agentStatus.currentAction = 'Wznawiam sesję po błędzie...';

            const newContent = `// Auto-generated by Test Monitor\nvar testData = ${JSON.stringify(testData, null, 2)};\n`;
            fs.writeFileSync(MONITOR_FILE, newContent, 'utf8');

        } else {
            // Stara sesja (> 5 min) = traktuj jako nową
            const ageMin = Math.round(ageMs / 60000);
            console.log('FRESH_START');
            console.error(`INFO: Stara sesja (${ageMin} min) - nowa sesja`);

            // Wyczyść starą sesję
            const nowStr = new Date().toISOString().slice(0, 19);
            testData.agentStatus = {
                isRunning: false,
                currentAction: null,
                lastAction: `Stara sesja wyczyszczona (${ageMin} min bez aktualizacji)`,
                finished: true,
                startedAt: agentStatus.startedAt,
                finishedAt: nowStr
            };
            testData.currentTest = null;
            if (testData.summary) {
                testData.summary.inProgress = 0;
            }

            const newContent = `// Auto-generated by Test Monitor\nvar testData = ${JSON.stringify(testData, null, 2)};\n`;
            fs.writeFileSync(MONITOR_FILE, newContent, 'utf8');
        }

    } catch (err) {
        console.log('FRESH_START');
        console.error(`ERROR: ${err.message}`);
    }
}

checkRestart();
