/**
 * Zatrzymuje monitor testów
 *
 * Rozróżnia:
 * - Błędy wewnętrzne (np. "is not defined") → NIE zamyka sesji, watchdog zrestartuje
 * - Zatrzymanie przez użytkownika → zamyka sesję
 *
 * Użycie:
 * node stop-monitor.js [reason]
 *
 * Przykłady:
 * node stop-monitor.js "Zatrzymany przez użytkownika"
 * node stop-monitor.js "classifyHandoffIfNeeded is not defined"
 */

const fs = require('fs');
const path = require('path');

const MONITOR_FILE = path.join(__dirname, '..', 'monitor', 'tests-data.js');
const RESTART_FLAG = path.join(__dirname, '..', 'monitor', 'needs-restart.txt');

// Wzorce błędów wewnętrznych które wymagają auto-restartu
const INTERNAL_ERROR_PATTERNS = [
    'is not defined',
    'undefined is not',
    'Cannot read property',
    'ECONNRESET',
    'ETIMEDOUT',
    'socket hang up',
    'network error',
    'internal error'
];

function isInternalError(reason) {
    const lowerReason = reason.toLowerCase();
    return INTERNAL_ERROR_PATTERNS.some(pattern =>
        lowerReason.includes(pattern.toLowerCase())
    );
}

function stopMonitor(reason = 'Agent zatrzymany') {
    try {
        // Odczytaj aktualny plik
        const content = fs.readFileSync(MONITOR_FILE, 'utf8');

        // Wyciągnij obiekt testData
        const match = content.match(/var testData\s*=\s*(\{[\s\S]*\});?\s*$/);
        if (!match) {
            console.error('Nie można sparsować pliku tests-data.js');
            process.exit(1);
        }

        let testData;
        try {
            testData = JSON.parse(match[1]);
        } catch (e) {
            console.error('Błąd parsowania JSON:', e.message);
            process.exit(1);
        }

        const now = new Date().toISOString().slice(0, 19);
        const internalError = isInternalError(reason);

        if (internalError) {
            // BŁĄD WEWNĘTRZNY - nie zamykaj sesji, pozwól watchdogowi zrestartować
            console.log('=== WYKRYTO BŁĄD WEWNĘTRZNY ===');
            console.log(`Reason: ${reason}`);
            console.log('Sesja NIE zostanie zamknięta - watchdog zrestartuje agenta');

            testData.lastUpdate = now;
            testData.agentStatus = {
                ...testData.agentStatus,
                // Pozostaw isRunning=true żeby watchdog mógł wykryć
                currentAction: `⚠️ Błąd wewnętrzny: ${reason.slice(0, 50)}... - oczekiwanie na restart`,
                lastError: reason,
                lastErrorAt: now
            };

            // NIE czyść currentTest - agent wznowi ten test

            // Utwórz flagę restartu
            fs.writeFileSync(RESTART_FLAG, `${now}\n${reason}`, 'utf8');
            console.log('Utworzono flagę restartu: needs-restart.txt');

        } else {
            // NORMALNE ZATRZYMANIE - zamknij sesję
            console.log('=== ZATRZYMANIE AGENTA ===');

            testData.lastUpdate = now;
            testData.agentStatus = {
                ...testData.agentStatus,
                isRunning: false,
                finished: true,
                currentAction: reason,
                finishedAt: now
            };

            // Wyczyść currentTest i inProgress
            testData.currentTest = null;
            if (testData.summary) {
                testData.summary.inProgress = 0;
            }

            // Usuń ewentualną flagę restartu
            if (fs.existsSync(RESTART_FLAG)) {
                fs.unlinkSync(RESTART_FLAG);
            }
        }

        // Zapisz plik
        const newContent = `// Auto-generated by Test Monitor\nvar testData = ${JSON.stringify(testData, null, 2)};\n`;
        fs.writeFileSync(MONITOR_FILE, newContent, 'utf8');

        console.log(`  Time: ${now}`);
        console.log(`  Internal error: ${internalError}`);

    } catch (err) {
        console.error('Błąd:', err.message);
        process.exit(1);
    }
}

// Uruchom z argumentami CLI
const reason = process.argv.slice(2).join(' ') || 'Agent zatrzymany';
stopMonitor(reason);
